### PR TITLE
includes several fixes

### LINKED ISSUE #10: Performance issues
Here is a screenshots
- https://tppr.me/TnQYK
- https://tppr.me/tVWNe

The performance of recase regex's adds a lot to the rendering time.
Are there any techniques for improving performance?

### PR DESCRIPTION
**Pull request by vasilich6107**
- performance fix #10 
- empty string crash fix
- code simplification #12

### CODE REVIEW

**Comment by vasilich6107** [comment]
Hi @nitehogg 
Could you review the PR?
Thanks)

File: lib/recase.dart [hunk 1]
```diff
@@ -1,36 +1,42 @@
...
 
   String originalText;
   List<String> _words;
-
   ReCase(String text) {
     this.originalText = text;
     this._words = _groupIntoWords(text);
   }
 
+  // TODO must be covered via tests
```
Comment (nitehogg) [inline lib/recase.dart]: Can you remove this comment? The method is private and there's no plan to expose it just for testing.

File: lib/recase.dart [hunk 2]
```diff
@@ -1,36 +1,42 @@
...
-  final RegExp _symbolRegex = new RegExp(r'[ ./_\-]');
+
+  final symbolMap = {
+    ' ': true,
+    '.': true,
+    '/': true,
+    '_': true,
+    '\\': true,
+    '-': true
+  };
```
Comment (nitehogg) [inline lib/recase.dart]: This doesn't serve any additional value as a map. Can you change it to an array?

**Review by nitehogg — CHANGES_REQUESTED** [review]

File: lib/recase.dart (hunk 2 above)
Comment (vasilich6107) [reply lib/recase.dart]: This map was introduced to make the `recase` faster.
Cause `array.contains` lookup takes more time then retrieving value from map

File: lib/recase.dart (hunk 1 above)
Comment (vasilich6107) [reply lib/recase.dart]: Removed

File: lib/recase.dart (hunk 2 above)
Comment (nitehogg) [reply lib/recase.dart]: Are you going to notice the difference, for 6 elements, enough to justify misusing a map?

Comment (vasilich6107) [reply lib/recase.dart]: This test states 

```dart
import 'package:recase/recase.dart';

void main() {
  final sw = Stopwatch()..start();
  var result = null;
  const N = 10000;
  for (var i = 0; i < N; i++) {
    result = ReCase('This is-Some_sampleText. YouDig?').titleCase;
  }
  print(
      'done in ${sw.elapsedMilliseconds} (${sw.elapsedMilliseconds / N} ms. per iteration)');
  print('$result');
}
```

```
WITH MAP

lib/test.dart: Warning: Interpreting this as package URI, 'package:recase/test.dart'.
done in 94 (0.0094 ms. per iteration)
This Is Some Sample Text You Dig?

WITH ARRAY

lib/test.dart: Warning: Interpreting this as package URI, 'package:recase/test.dart'.
done in 107 (0.0107 ms. per iteration)
This Is Some Sample Text You Dig?
```

So there is a difference. It you still prefer array - I'll will use array.

Comment (nitehogg) [reply lib/recase.dart]: I think the timing diff is negligible. It's not worth introducing an anti-pattern, in my opinion. So my preference would be an array.

I know the size of the the array is static, but the parsed string could vary in size. The intent of this lib was never to parse documents, even though I think some people will probably try to use it that way. 

The lib's intent to is handle conversion of common naming conventions... the key word being "naming". So it shouldn't be expected to handle massive amounts of text, and to change the casing on such things would be out of scope of the lib, because it's not meant to handle punctuations etc.

So what it boils down to is: I wouldn't expect extreme variations of the processing time, so a diff of 0.0013ms should be fine.

Comment (vasilich6107) [reply lib/recase.dart]: Fixed. Thanks for collaboration

Comment (nitehogg) [reply lib/recase.dart]: No problem. I was just thinking last night, maybe a Set would solve both of our concerns. I'd be ok with a Set. I'm not sure how it performs, but I'd be curious if it has a hint of a performance gain, due to all elements being unique.

Comment (vasilich6107) [reply lib/recase.dart]: Good point)
I'll test with set

Comment (vasilich6107) [reply lib/recase.dart]: Set did the thing!
```
LIST
done in 106 (0.0106 ms. per iteration)

SET
done in 94 (0.0094 ms. per iteration)
```

File: test/perf.test.dart [hunk 3]
```diff
@@ -0,0 +1,13 @@
+import 'package:recase/recase.dart';
```
Comment (nitehogg) [inline test/perf.test.dart]: Can you move this into `/tools`? Since it's not a unit test and would be kicked off manually. The PR should be good afterwards.

Comment (vasilich6107) [reply test/perf.test.dart]: Done!

**Review by nitehogg — APPROVED** [review]
Looks good. Thanks.
